name: bolha_ressonante
description: Bolha Ressonante
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  noise_meter: ^5.0.0

flutter:
  uses-material-design: true
